### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mansoorsamo85** [elgharabawy/WebEdit-Config-File-For-Bootstrap#1]
Good to see such type of support for notepad++. But still it needs to be add all classes of Bootstrap. So I have added one new for Bootsrap Panel heading with title which you have not included in your .ini file. please add the following code to file for bootstrap panel heading.

`bsPanelH=<div class="panel panel-default">\n\t<div class="panel-heading">\n\t\t<h3 class="panel-title">Panel Title</h3>\n\t</div>\n\t<div class="panel-body">\n\t\tBasic panel example\n\t</div>\n</div>`

Thanks
Regards,
Mansoor Samo

**Comment by elgharabawy** [comment]
I don't think this is an issue, rather, it's an addition. You could add anything you like actually. Just extend it however you see fit..
